src/apollo/pageContent/PageContent.tsx, src/common/components/htmlToReact/HtmlToReact.tsx, src/common/components/list/List.tsx, src/common/components/text/Text.tsx, src/core/index.ts, src/core/page/Page.stories.tsx, src/core/pageContent/PageContent.stories.tsx, src/core/pageContent/PageContent.tsx, src/core/pageContent/PageContentBreadcrumbs.tsx, src/core/pageContent/PageContentLayout.tsx, src/core/pageContent/PageMainContent.tsx, src/core/pageContent/__tests__/Page.test.tsx, src/core/pageContent/meta/PageMeta.tsx, src/core/pageContent/sidebarContent/SidebarContent.tsx, src/core/pageContent/sidebarContent/SidebarContentCard.tsx, src/core/pageContent/sidebarContent/SidebarContentLinkList.tsx, src/core/pageContent/sidebarContent/SidebarPostListItem.tsx
There were strange issues inside the build package. When the library was used by a client app, the PageContent was typed with the properties of the Text-component. These changes seems to have fixed the issue.
1. Renamed the exported Props. HCRC-13. Because of some build errors, the props are renamed to more be more unique and so more followable.
2. Export named functions only from PageContent. HCRC-13. Page content had some issues in a rollup build process. When the HCRC lib was used, the props from Text-component were used instead of the PageContentProps. Exporting the PageContent as a named function instead of default fixed the issue.
=> Fix to PageContent build issues

src/common/components/htmlToReact/HtmlToReact.tsx
HCRC-40. The HEadless CMS sets the widths (in pixels) as an inline style to the images. They need to be stripped out. Also the table looks cooler when it's always full width. The img-tag with it's own attributes also wrecked the global layout width (so e.g. the carousel was always rendered in "desktop mode")!
A screenshot from Kultus after the fixes:
=> Convert the table and the image widths to 100%

src/core/configProvider/defaultConfig.tsx, src/core/link/Link.tsx, src/core/linkBox/LinkBox.tsx
Refactored Linkbox
Added support of the routing link wrapper for the internal links. Now for the next projects we can pass the next/link
=> Routing refactoring part 3

package.json, src/common/components/tag/Tag.tsx, src/common/components/tag/tag.module.scss
Tags cannot be selected when no onclick event, so on click should be no outline style.
=> Tag fix outline

README.md, package.json, src/apollo/apollo.stories.tsx, src/common/eventsService/__generated__.ts, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/modules.graphql, src/core/collection/types.tsx, src/core/pageContent/PageContent.tsx, src/core/pageContent/utils.ts
Implemented `showAllLink` fetching from the CMS for article carousels. Event carousels don't have show all links at least for now. 
Also updated README about `yarn generate:graphql` not working with Node.js v16 or greater.
**[HCRC-78](https://helsinkisolutionoffice.atlassian.net/browse/HCRC-78): As a content manager I can add a show all -link in the carousel**
=> HCRC-78 | Article carousel show all links

package.json, src/common/headlessService/__generated__.ts, src/core/collection/Collection.tsx
HH-266. The event selection carousel uses the eventsByIds query. However, the LinkedEvents requires an event_type -attribute even then when fetching the events by ids. Added the 2 event types to the query-variables.
Before:
After:
=> Use event types when fetching events by ids from LinkedEvents

package.json, src/apollo/index.ts, src/common/headlessService/utils.ts
Export more types from the common headlessService and add a typeguard for Language type.
Related to HH-252 (https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/126)
=> Export more Language types

.env.example, .eslintignore, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/article.graphql, src/common/headlessService/graphql/modules.graphql, src/common/headlessService/graphql/page.graphql, src/common/venuesService/__generated__.ts
LIIKUNTA-329.
Removed the needless types from the venues schema.
Added the LocationsSelectedCarousel to the Headless CMS schema.
Included the LocationsSelectedCarousel in the page and article fragments.
=> chore(schema): updated the schemas

package.json, src/core/card/Card.stories.tsx, src/core/card/Card.tsx, src/core/card/card.module.scss
HH-283.
An arrow link inside a card can now have a label / text.
The label can be given as a parameter.
The text can be styled with card's style prop.
A screenshot from a storybook:
=> feat(card): arrow link label

package.json, src/core/carousel/carousel.module.scss
Arrows net and previous should be black on iphone.
=> carousel mobile styles fix

package.json, src/core/collection/Collection.tsx, src/core/collection/utils.ts
HH-254.
It's clear that there has been a bug in the normalized params usage, 
because the eventType was already handled, but the mutated params-object
was actually never used.
The boolean strings "true / "false" are now handled in that same params-object.
Also the transforming function is moved to the file meant for utils related 
to the Collection-component.
=> fix: convert booleans presented in string format to actual booleans

package.json, src/common/utils/testImage.ts, src/core/card/Card.tsx, src/core/card/LargeCard.tsx, src/core/hooks/useResolveImageUrl.ts, src/core/image/BackgroundImage.tsx, src/core/pageContent/PageContentLayout.tsx
LIIKUNTA-434
An undefined image url left the browser hanging and 
waiting for a request that could never succeed. 
Added a null value to image url type, because that
usually was the case where a fallback image was needed.
=> Reject an empty image url and offer a fallback immediately

package.json, src/core/link/LinkBase.module.scss
Size of the external icon stays the same (not getting smaller if multiple lines of text)
=> fix: link icon styles

package.json, src/core/card/largeCard.module.scss
Image to text ration 1.5:1 in the large event card
https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-517
=> fix: large card image ratio

package.json, src/common/eventsService/__generated__.ts, src/common/headlessService/__generated__.ts, src/mocks/queries/pageEventSelectionModule.ts
the changes in events-graphql-proxy were taken from a locally running
events-graphql-proxy, the version is from events-helsinki-monorepo
repository's PR #413:
- https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/413
=> chore: update types including events-helsinki-monorepo PR #413 changes

jest.config.js, package.json, src/core/collection/__tests__/Collection.test.tsx, src/core/utils/string.ts, yarn.lock
HH-234
The HCRC-lib was build properly and the storybook could be used,
but when it was used as a plugin in an app,
the app whined about that there were commonjs `module.exports`
inside the bundled esm javascript.
The issues was in the lodash-library that was used as a dependency and
was added quit recently. The lodash is now replaced with lodash-es,
which should fit better in esm and nextjs world.
----
When the events-monorepo app was ran with the new version of the HCRC, it whined about `es modules may not assign module.exports or exports.*`. When I investigated what the bundled HCRC code had inside the line  that the debugger reported, there was a clear `module.export` declaration. The `module.export` is a way to export objects when using the `commonjs`. The ESM-module should use the …
=> fix: change lodash to lodash-es in order to fix the bundle issues

src/core/link/LinkBase.scss
LIIKUNTA-484. 
Set the same outline style to focus-visible as was set to focus for HDS link base.
=> fix: link base focus-visible outline to mirror focus styles

package.json, src/core/card/Card.tsx
When card module has delimited param true, the click on the content does not work. PR fixes the issue
=> fix: card delimited url redirect

Dockerfile, package.json
`docker compose up --build` failed with node v16 that was used in
Dockerfile because some package required at least node v18. Updated node
to v20 in Dockerfile and it seems to work.
fixes package incompatibility:
```
error rollup-plugin-dts@6.0.0:
The engine "node" is incompatible with this module.
Expected version ">=v18.17.1". Got "16.20.2"
error Found incompatible module.
```
=> fix(docker): update node version to v20, previous v16 was incompatible

package.json, src/common/components/htmlToReact/HtmlToReact.stories.tsx, src/common/components/htmlToReact/HtmlToReact.tsx, src/common/components/htmlToReact/htmlToReact.module.scss, src/core/pageContent/__mocks__/pageWithDiverseContent.mock.ts, src/core/pageContent/pageMainContent.module.scss, src/core/styles/hdsCoreTable.module.scss
HtmlToReact:
- add htmlToReact.module.scss for all the styles needed by HtmlToReact
- wrap table.css from hds-core into hdsCoreTable.module.scss
- map <figure class="is-style-stripes"> to .hds-table--zebra style in
tables inside such figure
- always pass options to domToReact calls
- this makes it possible to move caption, thead and tbody tags'
handling into replaceDomNodeWithReactComponent because options has
replace function which uses replaceDomNodeWithReactComponent
- add to classNames (i.e. merge) instead of overwriting them
- add "with-vertical-lines" TableVariant
pageMainContent.module.scss:
- remove border styles for tables, they now come from HtmlToReact
also:
- set version to 1.0.0-alpha217
- add more example data using tables to storybook stories
refs LIIKUNTA-466 …
=> LIIKUNTA-466 | fix: fix table.css packaging, handle is-style-stripes style in figure

package.json, src/core/pageContent/pageMainContent.module.scss
pageMainContent.module.scss:
- remove conflicting paddings as they come from hds-core's table styles
via HtmlToReact now
refs LIIKUNTA-466
**[LIIKUNTA-466](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-466)**
**Showed to designer** in local environment and **they approved**
[LIIKUNTA-466]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIIKUNTA-466 | fix: fix HDS table padding by removing conflicting styles

src/core/card/Card.tsx, src/core/card/card.module.scss, src/core/pageContent/PageContent.tsx, src/core/pageModules/CardsModule/CardsModule.tsx, src/core/pageModules/CardsModule/Icon.tsx, src/core/pageModules/StepsModule/StepsModule.tsx, src/core/utils/createHashKey.ts
HCRC-106 HCRC-108.
When a layout cards module wsa used, the CMS pages went to an infite rerendering loop in apps.
This can be tested in Liikunta test-CMS-env with `/fi/pages/moduulitesti/`
----
Also fixed a style filling bug in Card-module:
Broken:
Fixed: 
Mobile:
=> Fix infinite loop with layout cards module

package.json, src/common/constants.ts, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx, src/core/navigation/Navigation.tsx, src/core/translation/__tests__/getTranslationWithFallback.test.tsx, src/core/translation/constants.ts, src/core/translation/getTranslationWithFallback.ts, src/core/translation/types.ts
add new config options under Config['copy']:
- headerActionBarLogoAlt
- headerActionBarLogoAriaLabel
- headerActionBarLogoSrc
- headerUniversalBarPrimaryLinkHref
- add localized URL fallbacks for each language
- headerUniversalBarPrimaryLinkText
also:
- split translation functionality into separate files and add tests for
getTranslationWithFallback
- set version to 1.0.0-alpha231
refs LIIKUNTA-582, LIIKUNTA-585 (work leftover from these tickets)
[LIIKUNTA-582](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-582)
[LIIKUNTA-585](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-585)
[LIIKUNTA-582]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> feat: make header logo and universal bar primary link configurable

jest.config.js, package.json, src/common/components/tag/Tag.tsx, src/common/components/tag/__tests__/Tag.test.tsx, tsconfig.json
HH-305 LIIKUNTA-593. 
There are some values that should be overridable.
While the HDS Tag-component still has a default value for an ID-property, it needs to overridable and automatically generated, if unset.
The id parameter is already deprecated with default value.
See more: https://github.com/City-of-Helsinki/helsinki-design-system/blob/master/packages/react/src/components/tag/Tag.tsx#L81).
=> feat: add id, role and size attributes to the tag component

src/core/collection/Collection.tsx, src/core/collection/__tests__/Collection.test.tsx
HCRC-89.
Skip events by ids query and render an empty collection when no event ids are given.
=> fix: skip collections' events by ids query when no ids are given

package.json, src/core/link/Link.stories.tsx, src/core/link/Link.tsx, src/core/link/LinkBase.module.scss, src/core/link/LinkBase.scss
- `mailto:` prefixed hrefs in `<Link>` use envelope icon to indicate email
- `tel:` prefixed hrefs in `<Link>` use phone icon to indicate telephone
also:
- fix `iconRight` style, it was not working at all before,
not it works similarly as `.hds-icon-left` but on the other side of
the link, except but had to make the large link's right icon's margin
zero to not make the margin too big
- set version to 1.0.0-alpha246
refs LIIKUNTA-445
[LIIKUNTA-445](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-445)
[LIIKUNTA-445]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIIKUNTA-445 | feat(link): handle mailto: and tel: prefixed hrefs in <Link> specially

package.json, yarn.lock
=> chore: upgrade hds-(react|core|design-tokens) packages to v3.3.0

package.json, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/configProvider/configContext.ts, src/core/pageContent/PageContent.tsx, src/core/pageContent/PageMainContent.tsx
- In all 3 apps article search now works with search query params (even though hcrc supports both state and url params search)
- Article page tags are redirecting to the article search with tag parameter (if app configured to use search query params, otherwise tags are not clickable)
- Fixed bug with clear search parameter
=> Articles search query

src/core/collection/Collection.stories.tsx, src/core/page/Page.stories.tsx, src/core/pageContent/PageContent.stories.tsx, src/core/pageContent/utils.ts
noticed getEventCardProps parameter count difference in events-helsinki-monorepo when fixing types:
- https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/607
refs HH-189
- [HH-189](https://helsinkisolutionoffice.atlassian.net/browse/HH-189)
- https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/607
[HH-189]: https://helsinkisolutionoffice.atlassian.net/browse/HH-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HH-189 | fix: fix calling getEventCardProps with wrong parameters

src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/navigation/Navigation.tsx, src/core/pageContent/PageContent.tsx
refs KK-1069 (noticed mainContentId not being used in Navigation)
[KK-1069](https://helsinkisolutionoffice.atlassian.net/browse/KK-1069)
[KK-1069]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: use mainContentId from Config in Navigation, use ?? instead of ||

package.json, src/core/link/Link.module.scss, src/core/link/Link.stories.tsx, src/core/link/Link.tsx, src/core/link/__tests__/Link.test.tsx, src/core/link/__tests__/__snapshots__/Link.test.tsx.snap, src/core/utils/__tests__/__snapshots__/findAllElementsOfType.test.tsx.snap, src/core/utils/__tests__/__snapshots__/getChildrenByType.test.tsx.snap, src/core/utils/__tests__/__snapshots__/recursiveMap.test.tsx.snap, src/core/utils/__tests__/findAllElementsOfType.test.tsx, src/core/utils/__tests__/getChildrenByType.test.tsx, src/core/utils/__tests__/recursiveMap.test.tsx, src/core/utils/findAllElementsOfType.ts, src/core/utils/getChildrenByType.ts, src/core/utils/recursiveMap.ts
HCRC-112.
If there is an image included in the Link children, the external link icon should not be rendered by default  for the external links. It can be forced with `showExternalIcon` prop.
Also fixed the styles of the secondary link.
In a secondary link, an anchor element had span for  text and another for the link icon. Both the subelements were displayed as flex, which made them to fill the whole row and rendering the icon in another row compared to the text.
=> Image link should not render the external link icon by default

package.json, src/core/index.ts, src/core/language/__tests__/languageSorter.test.tsx, src/core/language/constants.ts, src/core/language/findLanguage.ts, src/core/language/index.ts, src/core/language/languageSorter.ts, src/core/language/toPrimaryLanguageOption.ts, src/core/language/typeGuards.ts, src/core/language/types.ts, src/core/navigation/Navigation.tsx
also:
- bump version to v1.0.0-alpha253
refs LIIKUNTA-610
[LIIKUNTA-610](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-610)
The **language order** in the Navigation component in **storybook** is now "**Suomi Svenska English**",
i.e. Finnish, Swedish and English as intended:
Published as [canary build](https://www.npmjs.com/package/react-helsinki-headless-cms/v/1.0.0-alpha252-canary-8ff25d9) for testing with events-helsinki-monorepo in https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/627
[LIIKUNTA-610]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIIKUNTA-610 | fix: order languages in Navigation to order Finnish, Swedish & English

package.json, src/apollo/apollo.stories.tsx, src/common/eventsService/__generated__.ts, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/article.graphql, src/common/headlessService/graphql/page.graphql, src/core/index.ts, src/core/pageContent/PageContent.tsx, src/core/pageContent/utils.ts
LIIKUNTA-611.
Add breadcrumbs field to the page and the post query.
Add an utility that can be used to convert the uri-property to a link-property
and to clear the duplicated paths from the breadcrumbs.
=> feat: breadcrumbs included in the page and the post queries

package.json, yarn.lock
refs PT-1720
[PT-1720](https://helsinkisolutionoffice.atlassian.net/browse/PT-1720)
Published stable version https://www.npmjs.com/package/react-helsinki-headless-cms/v/1.0.0-alpha265
[PT-1720]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: upgrade to HDS v3.6.0, set version to 1.0.0-alpha265

package.json, src/core/navigation/Navigation.tsx
NOTE:
- Published as canary build [1.0.0-alpha269-canary-30a4d44](https://www.npmjs.com/package/react-helsinki-headless-cms/v/1.0.0-alpha269-canary-30a4d44) for testing
HDS v3.4–v3.6 has broken theme support with next.js SSR & hydration.
Using `style` instead of `theme` in HDS Header as a workaround.
refs PT-1720 (the broken behavior was uncovered as a part of this)
[PT-1720](https://helsinkisolutionoffice.atlassian.net/browse/PT-1720)
[PT-1720]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1720 | fix(navigation): override header max width using style instead of theme

package.json, src/core/navigation/Navigation.tsx
HDS v3.4–v3.7 has broken theme support with next.js SSR & hydration.
Using `style` instead of `theme` in HDS Header as a workaround.
bump version to v1.0.0-alpha273
refs PT-1720 (the broken behavior was uncovered as a part of this)
[PT-1720](https://helsinkisolutionoffice.atlassian.net/browse/PT-1720)
[PT-1720]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(navigation): override header max width using style instead of theme

package.json, src/core/pageContent/meta/PageMeta.tsx
When pasting the link to Miro, link is not displayed as a card. Og tags are not enough, but twitter tags should be provided to enable this feature.
=> fix: add meta tags

.env.example, package.json, src/constants.ts, src/core/navigation/__mocks__/navigationMenu.mock.ts, src/core/navigation/__mocks__/navigationUniversalBarMenu.mock.ts, src/core/page/Page.stories.tsx, src/core/pageContent/__mocks__/page.mock.ts, src/core/pageContent/__mocks__/pageWithDiverseContent.mock.ts, src/mocks/responses/cms/languages/hobbies-languages.json, src/mocks/responses/cms/page/kukkuu-page-demosivu.json, src/storybook-common/constants.ts
done:
- replace ".hkih.stage.geniem.io" with ".app-staging.hkih.hion.dev"
- replace "https://hkih.stage.geniem.io/" with
"https://app-staging.hkih.hion.dev/"
refs KK-1196 (kukkuu new CMS urls)
refs LIIKUNTA-669 (events-helsinki-monorepo new CMS urls)
refs PT-1751 (palvelutarjotin new CMS urls)
[KK-1196](https://helsinkisolutionoffice.atlassian.net/browse/KK-1196)
[LIIKUNTA-669](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-669)
[PT-1751](https://helsinkisolutionoffice.atlassian.net/issues/PT-1751)
[KK-1196]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIIKUNTA-669]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> Use new CMS urls

package.json, src/common/headlessService/__generated__.ts, src/core/pageContent/__mocks__/page.mock.ts, src/core/pageContent/__mocks__/pageWithDiverseContent.mock.ts, src/storybook-common/constants.ts
- CMS urls were changed in af07ac91b460b06111f78c9ae77ec2c4f2501ca8 but
the GraphQL schemas weren't updated
- update GraphQL schemas by running "yarn generate:graphql"
- fix incorrect kultus test image url & incorrect kultus CMS menu name
refs KK-1196 (kukkuu new CMS urls)
refs LIIKUNTA-669 (events-helsinki-monorepo new CMS urls)
refs PT-1751 (palvelutarjotin new CMS urls)
[KK-1196](https://helsinkisolutionoffice.atlassian.net/browse/KK-1196)
[LIIKUNTA-669](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-669)
[PT-1751](https://helsinkisolutionoffice.atlassian.net/issues/PT-1751)
[KK-1196]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIIKUNTA-669]: …
=> Upgrade GraphQL schemas & fix tests

src/core/card/Card.tsx, src/core/card/LargeCard.tsx, src/core/linkBox/LinkBox.module.scss, src/core/linkBox/LinkBox.tsx
The link is wrapping the card, and it breaks the height. so we have to add optional flex parameter, which fixes this case
**[TH-1341](https://helsinkisolutionoffice.atlassian.net/browse/TH-1341)**
[TH-1341]: https://helsinkisolutionoffice.atlassian.net/browse/TH-1341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: card height in carousel

src/common/eventsService/__generated__.ts, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/article.graphql, src/common/headlessService/graphql/modules.graphql, src/common/headlessService/graphql/page.graphql, src/common/venuesService/__generated__.ts, src/core/archiveSearchPage/ArchiveSearchPage.stories.tsx, src/core/pageContent/PageContent.tsx, src/core/pageContent/__mocks__/page.mock.ts, src/core/pageContent/sidebarContent/SidebarPostListItem.tsx, src/core/pageContent/utils.ts
LIIKUNTA-700.
The featured image document has a field `featuredImage.mediaItemUrl` which stores a value to the source of the original image uploaded to the CMS media library. Nowadays the media library offers also some combressed versions of the image: large, medium_large, medium and thumbnail. The original media might be huge measured in a size of the file, so it should not be used in web. However, the size "large" is nowhere in use and the medium_large that is used, is usually too weak in quality, to be used for example as a hero image.
This commit adds the large size and makes the featuredIamge document consistent, no matter where it used, it will now offer all the file sizes. It might be bad practise to request sizes of image that are not used, but this library is generic and it makes …
=> fix: image sizes should be consistent and include size "large"
