City-of-Helsinki/react-helsinki-headless-cms

.storybook/main.js, .storybook/preview.js, package.json, src/common/components/grid/Grid.tsx, src/common/components/grid/grid.module.scss, src/core/card/Card.stories.tsx, src/core/card/Card.tsx, src/core/card/LargeCard.stories.tsx, src/core/card/LargeCard.tsx, src/core/card/__mocks__/card.mock.ts, src/core/card/card.module.scss, src/core/card/largeCard.module.scss, src/core/cardsList/CardsList.stories.tsx, src/core/cardsList/CardsList.tsx, src/core/carousel/Carousel.stories.tsx, src/core/carousel/Carousel.tsx, src/core/carousel/carousel.module.scss, src/core/carousel/utils/utils.ts, yarn.lock
-basic implementation of card component (still have to be fixed, for example contradicting with carousel mobile and missing features)
-large card component (see issues above)
-simple grid, to display cards
-carousel component for cards
=> HCRC: Card, LargeCard, CardList, Grid, Carousel

src/common/components/externalLink/ExternalLink.tsx, src/common/components/linkWrapper/LinkWrapper.tsx, src/common/components/linkWrapper/linkWrapper.module.scss, src/common/components/tag/Tag.tsx, src/common/components/tag/tag.module.scss, src/core/card/Card.stories.tsx, src/core/card/Card.tsx, src/core/card/__mocks__/card.mock.ts, src/core/card/card.module.scss, src/core/carousel/Carousel.stories.tsx, src/core/carousel/Carousel.tsx, src/core/carousel/carousel.module.scss
-Added multiple properties to the card component
-Fixed accessibility issues
-Fixed carousel component
=> HCRC-12: Cards extended, carousel fixed

src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/page.graphql, src/common/headlessService/types.ts, src/common/headlessService/utils.ts, src/core/card/Card.tsx, src/core/cardsList/CardsList.tsx, src/core/carousel/Carousel.tsx, src/core/carousel/utils/utils.ts, src/core/collection/Collection.stories.tsx, src/core/collection/Collection.tsx, src/core/collection/collection.module.scss, src/core/collection/types.tsx, src/core/page/Page.stories.tsx, src/core/pageContent/PageContent.stories.tsx, src/core/pageContent/PageContent.tsx, src/core/pageContent/PageContentLayout.tsx, src/core/pageContent/__mocks__/page.mock.ts, src/core/pageContent/__tests__/Page.test.tsx, src/core/pageContent/sidebarContent/SidebarContent.tsx, src/core/pageContent/utils.ts
HCRC-13 HCRC-29 HCRC-30 HCRC-31.
=> Add a collection implementation

src/common/components/grid/grid.module.scss, src/common/components/tag/Tag.tsx, src/common/components/tag/tag.module.scss, src/common/headlessService/__generated__.ts, src/common/headlessService/articles.ts, src/common/headlessService/graphql/articles.graphql, src/common/headlessService/types.ts, src/common/utils/dates.ts, src/core/articlesSearchPage/ArticleSearchPage.stories.tsx, src/core/articlesSearchPage/ArticlesSearchPage.tsx, src/core/articlesSearchPage/articlesSearchPage.module.scss, src/core/articlesSearchPageContent/ArticlesSearchPageContent.tsx, src/core/articlesSearchPageContent/__mocks__/articles.mock.ts, src/core/articlesSearchPageContent/articlesSearchPageContent.module.scss, src/core/card/Card.tsx, src/core/card/LargeCard.stories.tsx, src/core/card/LargeCard.tsx, src/core/card/card.module.scss, src/core/card/largeCard.module.scss, src/core/cardsList/CardsList.stories.tsx, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx
-Implements the articles search page layout
-Fixed Card and Large card components
-Styling fixes
=> HCRC-12: Articles search page layout

src/core/card/Card.tsx, src/core/card/card.module.scss, src/core/carousel/carousel.module.scss, src/core/collection/Collection.stories.tsx, src/core/collection/Collection.tsx, src/core/collection/collection.module.scss, src/core/page/Page.stories.tsx, src/core/pageContent/__mocks__/page.mock.ts, src/core/pageContent/__mocks__/pageWithDiverseContent.mock.ts, src/core/pageContent/pageContentLayout.module.scss, src/core/pageContent/pageMainContent.module.scss
HCRC-13 Style fixes to Collection. Little margin changes to the Carousel. Using a collectionWrapper and a carouselWrapper to set the right width. Added some styles to Style to figures that are rendered from Headless CMS.
Still some scaling issues in the mobile view, but when zoomed out, it looks ok
=> Fixed the collection styles

src/core/collection/Collection.stories.tsx, src/core/collection/Collection.tsx
=> Added grid and carousel as Collection types

package.json, src/common/eventsService/__generated__.ts, src/common/eventsService/graphql/events.graphql, src/core/index.ts, src/core/pageContent/utils.ts, src/linkedEvents/utils/normalizeKey.ts, src/linkedEvents/utils/normalizeKeys.ts, src/linkedEvents/utils/normalizeLocalizedObject.ts
=> Fix the build process by removing the memoize from normalizeKeys

src/core/collection/Collection.tsx
=> Fix collection event card link routing

src/common/components/htmlToReact/HtmlToReact.tsx, src/common/components/text/Text.tsx, src/common/components/text/text.module.scss, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/article.graphql, src/core/carousel/Carousel.tsx, src/core/carousel/carousel.module.scss, src/core/collection/Collection.tsx, src/core/collection/collection.module.scss, src/core/hero/hero.module.scss, src/core/navigation/Navigation.tsx, src/core/page/page.module.scss, src/core/pageContent/PageContent.tsx, src/core/pageContent/PageContentLayout.tsx, src/core/pageContent/PageMainContent.tsx, src/core/pageContent/__tests__/__snapshots__/Page.test.tsx.snap, src/core/pageContent/pageContentLayout.module.scss, src/core/pageContent/pageMainContent.module.scss
-routing and navigation
-style issues in various components
=> Routing navigation fix

src/apollo/index.ts
Extended the exports of menu queries (for hh-33)
=> HH-33: Menu graphql exports

src/core/index.ts, src/core/link/Link.module.scss, src/core/link/Link.stories.tsx, src/core/link/Link.tsx, src/core/link/SecondaryLink.tsx
Different variants of the link components (tested in hobbies)
=> Link variants

src/core/configProvider/defaultConfig.tsx, src/core/link/Link.tsx
Allows to have no routed link wrapper
=> Link component fix

src/core/collection/Collection.tsx, src/core/collection/collection.module.scss, src/core/contentContainer/ContentContainer.tsx, src/core/contentContainer/contentContainer.module.scss, src/core/hero/Hero.tsx, src/core/hero/hero.module.scss, src/core/index.ts, src/core/page/page.module.scss, src/core/pageContent/PageContentLayout.tsx, src/core/pageContent/pageContentLayout.module.scss, src/core/pageContent/sidebarContent/SidebarContentCard.tsx, src/core/pageContent/sidebarContent/SidebarContentLinkList.tsx, src/core/pageContent/sidebarContent/SidebarPostListItem.tsx, src/core/pageContent/sidebarContent/sidebarContentCard.module.scss, src/core/pageContent/sidebarContent/sidebarContentLinkList.module.scss, src/core/pageSection/PageSection.stories.tsx, src/core/pageSection/PageSection.tsx, src/core/pageSection/pageSection.module.scss
=> Page layouts refactoring

src/common/components/list/list.module.scss, src/core/hero/hero.module.scss, src/core/pageContent/PageContentLayout.tsx, src/core/pageContent/pageContentLayout.module.scss, src/core/pageContent/pageMainContent.module.scss, src/core/pageContent/sidebarContent/SidebarContentLinkList.tsx, src/core/pageContent/sidebarContent/sidebarContentLinkList.module.scss, src/core/pageSection/PageSection.tsx, src/core/pageSection/pageSection.module.scss
-Fix back button style, blue outline on hover
-Fix margins:
Between main title, date and content
Sidebar header aligned with main header
Fix koros margins (now they are smaller)
Fix mobile margins so the page looks consistent in mobile
Fix default colors of koros
Fix margin between sidebar and main content (44px total)
=> HH-132: Article layout fixes

src/core/link/LinkBase.scss, src/core/pageContent/sidebarContent/SidebarContentCard.tsx, src/core/pageContent/sidebarContent/sidebarContentCard.module.scss
Changes for the single courses page
=> HH-132: Courses restyling

src/core/page/Page.tsx, src/core/page/page.module.scss
Page layout fixes, so that the layout fits whole page vertically and footer always in the bottom
=> HH -133: Layout fixes

src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss
=> Use a page section component in the archive page

src/common/eventsService/__generated__.ts, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/articles.graphql, src/common/headlessService/graphql/pages.graphql, src/common/headlessService/types.ts, src/core/archiveSearchPage/ArchiveSearchPage.stories.tsx, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/archiveSearchPageContent/__mocks__/articles.mock.ts, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss, src/core/cardsList/CardsList.stories.tsx, src/core/carousel/Carousel.stories.tsx, src/core/hero/hero.module.scss, src/core/index.ts
Added search and pagination features to the articles and pages query.
HCRC-63. HCRC-64. Filter posts and pages by a search term and a language.
=> Search and pagination features to the articles and pages query

src/common/components/tag/tag.module.scss, src/core/card/Card.tsx, src/core/card/card.module.scss, src/core/carousel/Carousel.tsx, src/core/carousel/carousel.module.scss, src/core/collection/Collection.tsx, src/core/collection/collection.module.scss, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx, src/core/linkBox/LinkBox.module.scss
- Fixed styling of the cards and carousels
- Removed load more feature in Collections but left in Carousels (if needed later)
- Fixed accessibility issue with Carousel (tab navigation for cards)
- Added show all link for Collections, but not implemented the links logic
- Fixed the initial amount of loaded items, and shown per slide
=> HCRC-62: Cards and carousels fixes

src/core/card/card.module.scss, src/core/carousel/Carousel.tsx, src/core/carousel/carousel.module.scss, src/core/collection/Collection.stories.tsx, src/core/collection/collection.module.scss, src/core/linkBox/LinkBox.module.scss
-Fixed margins of the carousel title
-Fixed spacing with and without dots
-Dots sizes
-Font sizes and linehights inside cards
-Fixed mobile view prev next buttons
-Fixed mobile view bug with categories
- Fixed outlines of the cards in carousels
=> Carousel fix styling

src/apollo/pageContent/PageContent.tsx, src/apollo/pageWithTemplateContent/PageWithTemplateContent.tsx, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/collection/Collection.tsx, src/core/collection/collection.module.scss
-Multicolor
-Fixed  fixed issue (now always centered)
=> fix: loading spinner improvement

src/core/pageContent/sidebarContent/SidebarContent.tsx, src/core/pageContent/sidebarContent/SidebarContentCard.tsx, src/core/pageContent/sidebarContent/sidebarContentCard.module.scss
- Restyled the contents of the sidebar article and page
- Fixed publishing date render
=> HH-118: Sidebar improvements

src/core/collection/Collection.stories.tsx, src/core/collection/Collection.tsx, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx
=> Refactored the showAllUrl to be used from props instead of config

src/core/collection/Collection.tsx, src/core/index.ts
=> Export getEventCollectionCards

src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/card/card.module.scss
Clear tags logic fix (clears also free text)
=> Tags filters logic fix

package.json, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx
-Fixed headings in Search page
=> feat: fix headings

src/core/collection/Collection.tsx
=> Fix carousels event id

package.json, src/common/components/tag/Tag.tsx, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/card/Card.tsx, src/core/card/LargeCard.tsx, src/core/card/card.module.scss, src/core/card/largeCard.module.scss, src/core/carousel/Carousel.tsx, src/core/collection/Collection.tsx, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx, src/core/pageContent/PageContent.tsx
Add the main tag to the page layout and main-content id configurable from hcrc config
=> skip content fix

package.json, src/common/components/tag/tag.module.scss, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss, src/core/card/card.module.scss, src/core/card/largeCard.module.scss, src/core/carousel/carousel.module.scss, src/core/collection/collection.module.scss, src/core/link/Link.module.scss, src/core/linkBox/LinkBox.module.scss
Changes to support theming from monorepo
=> Theme fixes

package.json, src/core/pageContent/PageMainContent.tsx
Fixed incorrect import in the component
=> html to react link fix

package.json, src/core/card/card.module.scss
Fix the Card image horizontal view with 8:6 ratio
=> Fix card image

package.json, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx, src/core/pageContent/meta/PageMeta.tsx
favicon fix based on hds teams recommendations
=> Favicon fix

package.json, src/core/pageContent/pageContentLayout.module.scss
=> link size fix in pagecontent

package.json, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss, src/core/collection/collection.module.scss, src/core/hero/hero.module.scss
Added props and default color values for article and article search pages
=> Theme extended props

package.json, src/common/components/tag/Tag.stories.tsx, src/common/components/tag/Tag.tsx, src/common/components/tag/tag.module.scss, src/common/components/tag/tagThemes.tsx, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/pageContent/PageMainContent.tsx, src/core/pageContent/pageMainContent.module.scss, yarn.lock
=> Tag component refactoring

package.json, src/common/components/tag/Tag.tsx, src/common/components/tag/tag.module.scss, src/common/components/tag/tagThemes.tsx, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx
=> Tags extended theming

package.json, src/core/card/LargeCard.stories.tsx, src/core/card/LargeCard.tsx, src/core/card/largeCard.module.scss
=> fix: large card mobile view same as card mobile view

package.json, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss
=> archive page search border removed

package.json, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss
Archive layout and search field outline fix
=> UI fixes archive page

package.json, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss, src/core/card/largeCard.module.scss
Fixed search button size issue
Tab large card navigation fixed
=> Fix archive page

package.json, src/constants.ts, src/core/pageContent/utils.ts
LIIKUNTA-319
Relates to https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/187
=> Use a fallback language when reading title to cards

package.json, src/constants.ts, src/core/collection/Collection.tsx, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx, src/core/pageContent/PageContent.tsx, src/core/pageContent/utils.ts
=> CardProps-utilities served as configurable by the app

package.json, src/common/eventsService/__generated__.ts, src/common/eventsService/graphql/events.graphql
=> Add some enrolment and location fields to the event field fragment

package.json, src/core/collection/Collection.tsx, src/core/collection/collection.module.scss
Fix spacings in collection carousels in mobile view
=> Collection spacing

package.json, src/common/components/text/text.module.scss
=> heading styles

package.json, src/core/collection/Collection.tsx, src/core/collection/utils.ts, src/core/configProvider/configContext.ts, src/core/index.ts
Other things:
- Fix the event selection collection by fetching all the selected events
- Fix the getArticlePageCardProps type
=> Show only available events in the event selection collection

package.json, src/core/card/card.module.scss, src/core/card/largeCard.module.scss
-Fixed cards
For mobile (280px is still bare minimum, otherwise we have to refactor heading sizes and other places)
=> Card mobile fix

package.json, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss, src/core/pageContent/PageContentLayout.tsx, src/core/pageContent/pageContentLayout.module.scss
-Fixed articles height layout issues
=> article layout height fixed

package.json, src/core/pageContent/__mocks__/page.mock.ts, src/core/pageContent/__tests__/__snapshots__/Page.test.tsx.snap, src/core/pageContent/pageContentLayout.module.scss
=> List styles

package.json, src/core/link/LinkBase.scss, src/core/link/LinkBase.tsx
Add span for the link contents for better styling 
=> link structure

package.json, src/common/components/text/text.module.scss, src/core/pageContent/PageContent.tsx, src/core/pageContent/PageContentLayout.tsx, src/core/pageContent/pageMainContent.module.scss
=> fix: heading styles for page content

.env.example, README.md, src/apollo/apollo-custom-template.stories.tsx, src/common/components/tag/Tag.stories.tsx, src/core/archiveSearchPage/ArchiveSearchPage.stories.tsx, src/core/card/Card.stories.tsx, src/core/card/LargeCard.stories.tsx, src/core/cardsList/CardsList.stories.tsx, src/core/carousel/Carousel.stories.tsx, src/core/collection/Collection.stories.tsx, src/core/link/Link.stories.tsx, src/core/linkBox/Link.stories.tsx, src/core/page/Page.stories.tsx, src/core/pageContent/PageContent.stories.tsx, src/core/pageSection/PageSection.stories.tsx, src/storybook-common/constants.ts, src/storybook-common/useCmsEndpointConfig.tsx
=> Improve the documentations

package.json, src/common/components/grid/grid.module.scss, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss, src/core/card/card.module.scss, src/core/collection/Collection.tsx, src/core/collection/collection.module.scss
=> Collection grid fix

package.json, src/core/navigation/Navigation.tsx
=> Navigation logo link

.github/workflows/CI.yml, .github/workflows/npm-publish-canary.yml, .github/workflows/npm-publish.yml, .storybook/main.js, .storybook/preview.js, jest-setup.ts, package.json, public/mockServiceWorker.js, src/core/collection/__tests__/Collection.test.tsx, src/core/collection/utils.ts, src/mocks/handlers.ts, src/mocks/queries/pageEventSelectionModule.ts, src/mocks/server.ts, src/tests/apolloConfig.tsx, yarn.lock
TH-1305 HCRC-85.
When checking whether the event is closed, if the ending time is null,
use the starting time as an ending time.
Also installed the MSW to mock Storybook and Jest responses and added the first MSW unit test.
=> Fix the event ending time check when checking if an event is closed

package.json, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss
=> Articles page clear button fix

package.json, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss
h2 tag fixed to h1 (article page title)
=> fix articles header

package.json, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/modules.graphql, src/core/collection/Collection.tsx, src/core/collection/collection.module.scss, src/core/collection/types.tsx, src/core/pageContent/utils.ts
=> Event search carousel show all link

package.json, src/core/collection/Collection.tsx, src/core/pageContent/utils.ts
=> Fix collection locale bug

package.json, src/core/collection/Collection.tsx
=> HCRC:93 sort events order fix

package.json, src/common/components/list/List.tsx, src/common/components/text/text.module.scss, src/core/pageContent/pageMainContent.module.scss, src/core/pageContent/sidebarContent/SidebarContentLinkList.tsx
- header styles
- images styles (with captions and without)
- fixed margins
- list styles
=> Page content styles

package.json, src/common/components/tag/tag.module.scss
=> fix: no outline for non clickable tags

package.json, src/core/card/largeCard.module.scss
=> large card styles

package.json, src/core/card/card.module.scss, src/core/link/LinkBase.module.scss, src/core/link/LinkBase.tsx
- card alignment fix
- link alignment fix
- 
=> fix: css issues

package.json, src/core/card/Card.tsx, src/core/card/card.module.scss, src/core/pageContent/PageContent.tsx, src/core/pageContent/pageContentLayout.module.scss, src/core/pageModules/CardModule/CardModule.tsx, src/core/pageModules/CardsModule/CardsModule.tsx, src/core/pageModules/CardsModule/SimpleCard.tsx, src/core/pageModules/ContentModule/ContentModule.tsx, src/core/pageModules/StepsModule/StepsModule.stories.tsx, src/core/pageModules/StepsModule/StepsModule.tsx, src/core/pageModules/pageModules.module.scss, src/core/styles/background.module.scss, src/core/utils/string.ts, yarn.lock
Multiple bugs fixed and features are added:
Bugs: 
- Carousel cards images not the same height (bug in hcrc delimited version) fixed
- Card hover title underscore and cursor pointed in delimited version fixed
- Cards module when 1 item horisontal view, the grid layout fixed to be flex full width
- Html content decoding for Content, Cards and steps modules
Features:
- For modules with configurable background now white theme for the content is defined for 4 dark background colors: coat of arms, bus, brick and tram.
=> fix: content modules improvements

package.json, src/common/components/htmlToReact/HtmlToReact.stories.tsx, src/common/components/htmlToReact/HtmlToReact.tsx, yarn.lock
packages:
- change version to 1.0.0-alpha216
- add hds-core 2.17.0 dependency
- upgrade hds-react & hds-design-tokens to 2.17.0
HtmlToReact:
- add tableVariants prop to components
- a combination of 'dark', 'dense', 'light' and 'zebra',
- default is ['light']
- example: ['light', 'zebra', 'dense']
- add table test example to storybook where one can play with the
combinations of table variants
- table styling works by injecting HDS core table styles into elements:
- \<table\> -> "hds-table" + "hds-table--\<tableVariant\>" for each value
in tableVariants
- \<caption\> -> "hds-table__caption"
- \<tbody\> -> "hds-table__content"
- \<thead\>
- \<tr\> -> "hds-table__header-row"
refs LIIKUNTA-466
**[LIIKUNTA-466](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-466)**
**Testable** …
=> LIIKUNTA-466 | feat: style tables in HtmlToReact using HDS core styles, use hds* v2.17

.github/workflows/CI.yml, .github/workflows/npm-publish-canary.yml, .github/workflows/npm-publish.yml
=> chore: use node 20 in github workflows

package.json, src/core/hero/Hero.tsx
=> fix: show image with no title

package.json, src/core/hero/Hero.tsx, src/core/hero/hero.module.scss, src/core/pageContent/PageContent.tsx, src/core/pageContent/PageContentLayout.tsx, src/core/pageContent/PageMainContent.tsx, src/core/pageContent/pageContentLayout.module.scss, src/core/pageContent/pageMainContent.module.scss, src/core/pageModules/pageModules.module.scss
=> fix: hero ui tweaks

package.json, src/common/venuesService/__generated__.ts, src/common/venuesService/graphql/venues.graphql, src/core/card/Card.tsx, src/core/collection/Collection.tsx, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx, src/core/pageContent/utils.ts
=> Card title icon support and helsinki icon checkbox

package.json, src/core/pageContent/PageContent.tsx
=> fix: card module delimited alignment support

package.json, src/core/card/card.module.scss, src/core/pageSection/pageSection.module.scss
Fixed the height of the card with bg and no extra space (min height is not defined but automatic)
Possible fix to koros 1px line
=> fix: card height improvements and koros 1px

package.json, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx
Hide load more button while loading items
=> fix: load more button hide

package.json, src/core/archiveSearchPageContent/archiveSearchPageContent.module.scss
Configurable search button styles
=> Styles fixes article search component

package.json, src/common/headlessService/utils.ts, src/core/collection/__tests__/Collection.test.tsx, src/core/pageContent/sidebarContent/SidebarContentLinkList.tsx, src/core/pageContent/sidebarContent/__tests__/SidebarContent.test.tsx, src/core/pageContent/sidebarContent/__tests__/__snapshots__/SidebarContent.test.tsx.snap, src/core/pageContent/types.ts, tsconfig.json, yarn.lock
=> fix: sidebar content should skip the link items without an url

package.json, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/menu.graphql
=> Smaller menu item fragment can be fetched conditionally

package.json, src/core/card/card.module.scss, src/core/pageContent/pageContentLayout.module.scss, src/core/pageModules/StepsModule/StepsModule.tsx
- Fixed sidebar top margin
- Fixed card module mih height of the content area
- Fixed encoding of the Steps module step title
=> Fix article page

package.json, src/common/components/grid/Grid.stories.tsx, src/common/components/htmlToReact/HtmlToReact.stories.tsx, src/common/components/list/List.stories.tsx, src/common/components/tag/Tag.stories.tsx, src/common/components/text/Text.stories.tsx, src/common/components/text/text.module.scss, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/card/Card.stories.tsx, src/core/cardsList/CardsList.stories.tsx, src/core/carousel/Carousel.stories.tsx, src/core/collection/Collection.stories.tsx, src/core/contentContainer/ContentContainer.stories.tsx, src/core/hero/Hero.stories.tsx, src/core/hero/Hero.tsx, src/core/link/Link.stories.tsx, src/core/linkBox/Link.stories.tsx, src/core/storyContainer/StoryContainer.tsx, src/core/storyContainer/storyContainer.module.scss
- Fixed the article search page stories
- Improved documentation and stories in common and core components
**[HCRC-107](https://helsinkisolutionoffice.atlassian.net/browse/HCRC-107):**
[HCRC-107]: https://helsinkisolutionoffice.atlassian.net/browse/HCRC-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: improve stories and documentation

jest.config.js, package.json, yarn.lock
=> fix: upgrade hds-react to address issues with global css

package.json, src/common/components/text/text.module.scss
=> LIIKUNTA-621 | fix: strong text size

package.json, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/article.graphql, src/common/headlessService/graphql/page.graphql, src/core/archiveSearchPageContent/__mocks__/articles.mock.ts, src/core/archiveSearchPageContent/__mocks__/pageChildrenSearch.mock.ts, src/core/archiveSearchPageContent/__mocks__/pages.mock.ts, src/core/link/LinkBase.tsx, src/core/pageContent/__mocks__/page.mock.ts, src/core/pageContent/sidebarContent/SidebarCardsList.tsx, src/core/pageContent/sidebarContent/SidebarContent.tsx, src/core/pageContent/sidebarContent/sidebarCardsList.module.scss
**[HCRC-105](https://helsinkisolutionoffice.atlassian.net/browse/HCRC-105):**
[HCRC-105]: https://helsinkisolutionoffice.atlassian.net/browse/HCRC-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Sidebar cards module support

package.json, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/article.graphql, src/common/headlessService/graphql/modules.graphql, src/common/headlessService/graphql/page.graphql, src/core/pageContent/utils.ts
=> Fix carousel image sizes

package.json, src/core/navigation/Navigation.tsx, yarn.lock
refs LIIKUNTA-627 (HDS v3.7 might help here)
refs PT-1720 (HDS v3.7 might help here)
[LIIKUNTA-627](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-627) & https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/667
[PT-1720]([LIIKUNTA-627]())
[LIIKUNTA-627]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PT-1720]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIIKUNTA-627]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: upgrade to HDS v3.7, bump version to v1.0.0-alpha272

package.json, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx
Archive title uses the page title prop with fallback to config value
=> fix: archive page title improvements

package.json, src/core/collection/Collection.tsx
Css change is not needed, its already implemented correctly
=> fix: carousels heading h1 to h2

package.json, yarn.lock
refs KK-1152
https://github.com/City-of-Helsinki/kukkuu-ui/pull/569
=> feat: upgrade to HDS v3.8, bump version to v1.0.0-alpha279

package.json, src/core/link/LinkBase.scss
Added margin between link icon right. 
=> fix: css link icon right

package.json, src/core/card/Card.stories.tsx, src/core/card/Card.tsx, src/core/card/card.module.scss, src/core/pageContent/PageContent.tsx, src/core/styles/background.module.scss
Delimited option added, centered fixed
=> Card improvments

package.json, src/core/card/Card.tsx, src/core/card/card.module.scss
- change left and right positioning of the card content
- fix the bug with hover with no link defined
=> LIIKUNTA-664 | fix: card link hover and let right position switch

package.json, src/core/card/Card.tsx
=> fix: link default bg color

package.json, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx, src/core/imageGallery/Lightbox.tsx, src/core/navigation/Navigation.tsx, yarn.lock
1. update HDS to 3.9 version
2. Add hamburger menu translations
3. HCRC: fix single image module to hide action buttons and implement hamburger menu translations
=> HCRC-114 | feat: HDS 3.9

package.json, src/core/card/card.module.scss
=> fix: card content height

package.json, src/common/headlessService/__generated__.ts, src/common/headlessService/graphql/article.graphql, src/common/headlessService/graphql/modules.graphql, src/common/headlessService/graphql/page.graphql, src/common/headlessService/types.ts, src/common/headlessService/utils.ts, src/core/configProvider/configContext.ts, src/core/configProvider/defaultConfig.tsx, src/core/pageContent/PageContent.tsx, src/core/pageModules/SocialMediaFeedModule/SocialMediaFeedModule.stories.tsx, src/core/pageModules/SocialMediaFeedModule/SocialMediaFeedModule.tsx
Social feed module support
**[HCRC-98](https://helsinkisolutionoffice.atlassian.net/browse/HCRC-98):**
[HCRC-98]: https://helsinkisolutionoffice.atlassian.net/browse/HCRC-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Hcrc 98 social feed

package.json, src/core/card/card.module.scss
=> fix: card height in the carousel

package.json, src/core/archiveSearchPageContent/ArchiveSearchPageContent.tsx, src/core/configProvider/configContext.ts
=> Archive page load more button fix

package.json, src/core/navigation/Navigation.tsx
**[KK-1188](https://helsinkisolutionoffice.atlassian.net/browse/KK-1188):**
[KK-1188]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Navigation render fix

package.json, src/core/pageContent/PageContent.tsx, src/core/pageContent/__mocks__/page.mock.ts
**[LIIKUNTA-464](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-464):**
[LIIKUNTA-464]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: hero image size

package.json
=> v1 major release package

package.json, src/core/notification/Notification.tsx
Fix routing of internal hrefs in Notification
- **[KK-1424](https://helsinkisolutionoffice.atlassian.net/browse/KK-1424)**
- https://github.com/City-of-Helsinki/kukkuu-ui/pull/669
[KK-1424]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KK-1424 | Fix routing of internal hrefs in Notification
